### ISSUE TITLE
Scale factors are not changing with new trc file inputs

### ISSUE THREAD

**Issue by GEMcConnochie** [mapclient-plugins/fieldworklowerlimb2sidegenerationstep#6]
I am trying to run a simple scaling workflow using a static trc file as shown. I have tried with multiple different files, including an extreme example where the coordinates of the markers were multiplied by 1.5.  I can see from the log that the new marker coordinates are being read in correctly, but each time I am getting the same scale factors.  Any ideas where this issue could be coming from? I have tried completely reinstalling MAPClient but am still having the same issue. Thanks

![image](https://user-images.githubusercontent.com/89376037/223313102-c508081e-652a-45aa-b598-a2c1eb10e716.png)

![image](https://user-images.githubusercontent.com/89376037/223312380-be8eacde-061f-43cb-99a0-d55022306669.png)

**Comment by hsorby** [comment]
I think this is a problem that we are trying to resolve in the [GIAS3](https://github.com/musculoskeletal/gias3) library. We are still working on figuring out why the scaling is not taking place.

**Comment by GEMcConnochie** [comment]
Thanks for getting back to me. I am actually using Gias2 with the python 2 and the setup described here: https://wiki.auckland.ac.nz/display/ABI/The+MAP Is the same issue known with this version?

**Comment by hsorby** [comment]
I cannot say sorry, although this might be helpful for us in getting to the cause of this issue.  We will try and have a look at this in the next few days and report back on what, if any, progress we make.

**Comment by GEMcConnochie** [comment]
Never mind, I realised I needed to do both auto and manual registration to get it to work properly!
