### ISSUE TITLE
ModuleNotFoundError: No module named 'musculoskeletal'

### ISSUE THREAD

**Issue by lingfengbetter** [mapclient-plugins/fieldworklowerlimb2sidegenerationstep#7]
Thank you very much for your contribution, when I import the plugin into MAP, this error occurs,‘’ModuleNotFoundError: No module named 'musculoskeletal'‘’， please give me more information about the _musculoskeletal module_ , thanks again, hope I didn't waste your time.

**Comment by hsorby** [comment]
We have moved some things around you now need this package: https://pypi.org/project/musculoskeletal-models/ available from PyPI to use this plugin.  I'm not sure how you are setup up but if you are using a virtual environment then simply `pip install musculoskeletal-models` should solve this issue.

**Comment by lingfengbetter** [comment]
Thanks for your reply, this issue has been resolved
